name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "13 22 * * *"
    - cron: "7 14 * * *"

jobs:
  update-readme:
    name: Update Coding Stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SECTION_NAME: waka
          BLOCKS: -→
          TIME_RANGE: all_time
          LANG_COUNT: 8
          SHOW_TIME: true
          SHOW_TOTAL: true
          STOP_AT_OTHER: true
          COMMIT_MESSAGE: "Updated waka-readme graph with new metrics"
